### PR TITLE
Add golang-style testing to build-tools

### PR DESCRIPTION
**Pull request by rfay**
One of the difficulties of build-tools testing is that it hasn't had its own code to test against. This adds a tests directory with golang tests in it which actually tests operations of the build.

* Test the binary builds
* Test "make version" and related
* Test version overrides in code
* Tests gofmt success and failure
* Test golint, govendor, govet targets
* Has a simple unit test as well.

In general it is not trying to change the actual build, although some of the targets like `make govendor` were inadequately implemented and the tests immediately showed it, so those were improved.

I't complex because it's running "make" under "make", and creating errors and fixing them as it goes, especially `make govendor`

Review suggestions:
* Read the build_tools_test.go critically
* Run `make test` in the testing directory
* Try this out on a repository close to you. You would have to copy the contents into the repo rather than using the update script, because it only works against a tagged release.

### CODE REVIEW

**Comment by beeradb** [comment]
Running tests I see some strange output:

```
build-tools/tests ‹gke:bbowman› git:(20170223_add_golang_testing) » make test
go test -v -installsuffix "static" -ldflags "-X github.com/drud/build-tools/tests/pkg/version.VERSION=1.0-32-ge23ec35 -X github.com/drud/build-tools/tests/pkg/version.VERSION=1.0-32-ge23ec35" ./cmd/... ./pkg/...
?   	github.com/drud/build-tools/tests/cmd/build_tools_dummy	[no test files]
Password:
```

Odd that it's prompting for a password there without context.

I also wonder if we should have a README in the tests directory with an overview of make targets, similar to what we do in repos we pull the build-tools into?

**Comment by rfay** [comment]
This is a good point. The "make clean" on linux requires a sudo because container builds leave stuff on the local filesystem owned by anotehr user. You don't have passwordless sudo on your mac. I'll have to figure something out for that, it's a legitimate concern. The container build runs as root in order to put stuff into what it thinks is /usr/local/bin. Probably an easier way to do that. Perhaps the "make clean" should be done in side the container.

**Comment by beeradb** [comment]
Running a `sudo ls` to get the password prompt out of the way does get me past the password prompt, but oncovers another potential issue:

```
build-tools/tests ‹gke:bbowman› git:(20170223_add_golang_testing) » make test
go test -v -installsuffix "static" -ldflags "-X github.com/drud/build-tools/tests/pkg/version.VERSION=1.0-32-ge23ec35 -X github.com/drud/build-tools/tests/pkg/version.VERSION=1.0-32-ge23ec35" ./cmd/... ./pkg/...
?   	github.com/drud/build-tools/tests/cmd/build_tools_dummy	[no test files]
=== RUN   TestBuild
Current Directory: /Users/beeradb/Projects/go/src/github.com/drud/build-tools/tests
--- PASS: TestBuild (24.80s)
=== RUN   TestGoFmt
--- PASS: TestGoFmt (3.75s)
=== RUN   TestGovendor
--- PASS: TestGovendor (71.57s)
=== RUN   TestGoLint
--- FAIL: TestGoLint (4.43s)
        Error Trace:    build_tools_test.go:143
	Error:      	An error is expected but got nil.
        Error Trace:    build_tools_test.go:144
	Error:      	"Checking golint: bash: golint: command not found
	            	" does not contain "exported function DummyExported_function should have comment"
=== RUN   TestGoVet
--- PASS: TestGoVet (6.58s)
=== RUN   TestSuccessfulMath
--- PASS: TestSuccessfulMath (0.01s)
FAIL
FAIL	github.com/drud/build-tools/tests/pkg/clean	111.190s
?   	github.com/drud/build-tools/tests/pkg/dirtyComplex	[no test files]
?   	github.com/drud/build-tools/tests/pkg/version	[no test files]
make: *** [test] Error 1
```

**Comment by rfay** [comment]
Definitely weird. I would assume you don't have golint installed on your  computer, and somehow this isn't being done in the container, which is a bad thing.. Oh so great to test in different environments!

Followup: 
* Test each target (gofmt, golint, govendor, etc.) on a host which does not have those installed.

**Comment by rfay** [comment]
Updated to add tag for golang-build-container, and hopefully remove need to run the container as root; now running it as uid:gid of the user. We'll see if that works for circle when it comes back (works ok on my linux VM).

**Comment by rfay** [comment]
I think all the issues so far have been taken care of. Great comments and discoveries on this one.

**Comment by beeradb** [comment]
Getting back to this. Here's my output when I run make darwin:

```
build-tools/tests ‹gke:drud-test› git:(20170223_add_golang_testing) » make darwin
building darwin from ./cmd/... ./pkg/...
Unable to find image 'drud/golang-build-container:0.1.0' locally
0.1.0: Pulling from drud/golang-build-container
00d19003217b: Already exists
bb658c9d1694: Already exists
91e373d2997a: Already exists
a9ea7e9ad7d8: Already exists
956baf7c50c1: Already exists
e7bb88a66400: Already exists
629f5ba9ab0d: Already exists
2c3e8b1009d8: Already exists
3b7e579721c7: Already exists
d62319ddce58: Already exists
cfbb68e97cd6: Already exists
bfb99d9ecc9c: Already exists
3b34cab8d6e5: Pull complete
e57f3e6a7b61: Pull complete
489d48d1254a: Pull complete
Digest: sha256:6652a410a2db826e02af55edb626b87712670bea099b1af1f857ec20cc49629a
Status: Downloaded newer image for drud/golang-build-container:0.1.0
```

That feels a bit confusing because most of the output is related to a docker pull. There's no indication of success or failure. Just brainstorming, but it may make things more obvious to either:

1. Hide the output from docker pull
2. Echo a simple success message at the end of the build

**Comment by beeradb** [comment]
I also tested other targets (gofmt, govendor, golint) and got the following output. I am thinking this is expected, despite the 'failures', since tests appear to check them (and pass):


```
build-tools/tests ‹gke:drud-test› git:(20170223_add_golang_testing) » make golint
Checking golint: Golint problems discovered: pkg/dirtyComplex/bad_golint_code.go:5:1: exported function DummyExported_function should have comment or be unexported
pkg/dirtyComplex/bad_golint_code.go:5:6: don't use underscores in Go names; func DummyExported_function should be DummyExportedFunction
make: *** [golint] Error 1
build-tools/tests ‹gke:drud-test› git:(20170223_add_golang_testing) » make govendor
Using govendor to check for missing dependencies and unused dependencies: %                                                                                                                                                                                                   build-tools/tests ‹gke:drud-test› git:(20170223_add_golang_testing) » make gofmt
Checking gofmt:
These files need gofmt -w: pkg/dirtyComplex/bad_gofmt_code.go
make: *** [gofmt] Error 1
```

**Comment by rfay** [comment]
Yes, there are deliberate errors introduced for testing. The test script tests the "clean" package for success and the "dirty" package for failures. 

I'm fine with a "success" output; we could also remove the '@' from in front of the docker command.  I might like that better.

**Pull request merged**
